### ISSUE TITLE
Add source code support: *.pas, *.go, *.c, *.cpp, *.h, *.hpp,*.hxx,*.cxx, *.dpr, *.pp, *.cs, *.js, *.java, *.py

### ISSUE THREAD

**Issue by SkybuckFlying** [BBC-Esq/VectorDB-Plugin-for-LM-Studio#228]
Applicability: Source code translation, understanding, debugging, generation, documentation

**Comment by SkybuckFlying** [comment]
I want this software to scan my source code files and add them to the AI, so I can question the AI, for example:

Convert Go code to Delphi code, during the conversion the AI will know about certain types thanks to the scanning of the source code files.

**Comment by BBC-Esq** [comment]
Unfortunately this program is geared towards a single question-answer situation.  For example, you could ask "How does this script address the issue of multithreading when running the large language chat model?"  And the response would be an explanation and possibly some quotes from the relevant script.  However, it would not be able to rewrite anything, unfortunately.  This is because the question you send is used to search the database is used to retrieve relevant contexts.  Thus, if your question is "Convert Go code to Delphi code" it wouldn't be able to search the database efficiently...kind of hard to explain.

**Comment by SkybuckFlying** [comment]
OK, it would still be usefull to be able to question the source code...

**Comment by BBC-Esq** [comment]
It could be awhile until I can get something working, but I thought you'd like this link in the meantime.  It's pretty effective based on my limited testing.

https://app.greptile.com/

**Comment by BBC-Esq** [comment]
Unfortunately I had to cancel this feature request.  I researched the issue and I'd need a specific embedding model geared towards coding languages and Huggingface doesn't have any decent ones...hardly any at all, actually.  Sorry.

**Comment by SkybuckFlying** [comment]
> It could be awhile until I can get something working, but I thought you'd like this link in the meantime. It's pretty effective based on my limited testing.
> 
> https://app.greptile.com/

Thanks but it only works for repos smaller than 10 MB, so not very usefull for now.
